name: admin
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.1.0+6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.7
  cupertino_icons: ^1.0.4
  firebase_core: ^1.12.0
  flutter_html: ^2.2.1
  http: ^0.13.4
  intl: ^0.17.0
  line_icons: ^2.0.1
  provider: ^6.0.2
  shared_preferences: ^2.0.12
  url_launcher: ^6.0.18
  google_fonts: ^2.2.0
  fluttertoast: ^8.0.8
  dropdown_search: ^3.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:

    - family: Muli
      fonts:
        - asset: assets/fonts/Muli-Light.ttf
          weight: 400
        - asset: assets/fonts/Muli-Regular.ttf
          weight: 500
        - asset: assets/fonts/Muli-Medium.ttf
          weight: 600
        - asset: assets/fonts/Muli-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Muli-Bold.ttf
          weight: 800

  assets:

    - assets/images/icon.png
